CREATE TABLE IF NOT EXISTS quizzes (
  id SERIAL PRIMARY KEY,
  pin VARCHAR(6) UNIQUE NOT NULL,
  title VARCHAR(255) NOT NULL,
  questions JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(10) DEFAULT 'active'
);
