name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

env:
  NODE_VERSION: '20.x'
  AZURE_WEBAPP_NAME: bistecquizz-backend-dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install Dependencies
      run: |
        cd backend
        npm install

    - name: Prepare for production
      run: |
        cd backend
        # Create a production build directory
        mkdir -p build
        # Copy necessary files
        cp package.json build/
        cp -r server.js config controllers middleware models routes services build/
        cd build
        # Install production dependencies
        npm install --production
        # Create a startup command file
        echo "cd /home/site/wwwroot && npm start" > startup.sh
        chmod +x startup.sh

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.BACKEND_PUBLISH_PROFILE }}
        package: backend/build
        startup-command: "/home/site/wwwroot/startup.sh"
        app-settings: |
          PORT=8080
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
          WEBSITE_NODE_DEFAULT_VERSION=~20
          SCM_DO_BUILD_DURING_DEPLOYMENT=false