name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

env:
  NODE_VERSION: '20.x'
  AZURE_WEBAPP_NAME: bistecquizz-frontend-dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install Dependencies
      run: |
        cd frontend
        npm install

    - name: Build
      env:
        VITE_BACKEND_URL: https://bistecquizz-backend-dev.azurewebsites.net
      run: |
        cd frontend
        npm run build

    - name: Prepare for deployment
      run: |
        cd frontend/dist
        npm install -g pm2
        echo "pm2 serve /home/site/wwwroot --no-daemon --spa" > startup.sh
        chmod +x startup.sh

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.FRONTEND_PUBLISH_PROFILE }}
        package: frontend/dist

    - name: Configure startup command
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp config set --resource-group bistecquizz-dev-rg --name ${{ env.AZURE_WEBAPP_NAME }} --startup-file /home/site/wwwroot/startup.sh --linux-fx-version "NODE|20-lts"